export const info = {
  name: "",
  technology: "",
  Roll: "",
  RegistrationNo: "",
  Session: "",
  Semester: "",
  Shift: "",
};

export const depertment = [
  { id: 1, depertment: "প্রিন্টিং বিভাগ" },
  { id: 2, depertment: "অফসেট প্রিন্টিং ল্যাব" },
  { id: 3, depertment: "demo" },
  { id: 4, depertment: "demo" },
  { id: 5, depertment: "demo" },
  { id: 6, depertment: "demo" },
  { id: 7, depertment: "demo" },
  { id: 8, depertment: "demo" },
  { id: 9, depertment: "demo" },
  { id: 10, depertment: "demo" },
  { id: 11, depertment: "demo" },
  { id: 12, depertment: "demo" },
  { id: 13, depertment: "demo" },
  { id: 14, depertment: "demo" },
  { id: 15, depertment: "demo" },
  { id: 16, depertment: "demo" },
  { id: 17, depertment: "demo" },
  { id: 18, depertment: "demo" },
  { id: 19, depertment: "demo" },
  { id: 20, depertment: "demo" },
  { id: 21, depertment: "demo" },
  { id: 22, depertment: "demo" },
  { id: 23, depertment: "demo" },
  { id: 24, depertment: "demo" },
  { id: 25, depertment: "demo" },
  { id: 26, depertment: "demo" },
  { id: 27, depertment: "demo" },
  { id: 28, depertment: "demo" },
  { id: 29, depertment: "demo" },
  { id: 30, depertment: "demo" },
  { id: 31, depertment: "demo" },
];
