export const info = {
  name: "",
  technology: "",
  Roll: "",
  RegistrationNo: "",
  Session: "",
  Semester: "",
  Shift: "",
};

export const depertment = [
  { id: "১", depertment: "প্রিন্টিং বিভাগ" },
  { id: "ক", depertment: "অফসেট প্রিন্টিং ল্যাব" },
  { id: "খ", depertment: "লেটার প্রেস প্রিন্টিং ল্যাব" },
  { id: "গ", depertment: "গ্রাভিয়ার প্রিন্টিং ল্যাব" },
  { id: "ঘ", depertment: "ফ্লেক্সে গ্রাফিক প্রিন্টিং ল্যাব" },
  { id: "ঙ", depertment: "বাইন্ডিং ফিনিশিং ল্যাব" },
  { id: "চ", depertment: "ডিজিটাল প্রিন্টিং ল্যাব" },
  { id: "ছ", depertment: "প্লেট মেকিং ল্যাব" },
  { id: "জ", depertment: "স্ত্রী প্রিন্টিং ল্যাব" },
  { id: "ঝ", depertment: "ফটো এনগ্রেভিং" },
  { id: "২", depertment: "গ্রাফিক ডিজাইন" },
  { id: "ক", depertment: "ক্যামেরা ল্যাব" },
  { id: "খ", depertment: "ভিডিও এডিটিং ল্যাব" },
  { id: "গ", depertment: "ডিটিপি ল্যাব-১ " },
  { id: "ঘ", depertment: "ডিটিপি ল্যাব-২" },
  { id: "ঙ", depertment: "ডিটিপি ল্যাব-৩" },
  { id: "চ", depertment: "ডিজাইন লাব-১" },
  { id: "ছ", depertment: "ডিজাইন লাব-2" },
  { id: "৩", depertment: "কম্পিউটার বিভাগ" },
  { id: "ক", depertment: "কম্পিউটার ল্যাব " },
  { id: "খ", depertment: "ইলেকট্রনিক ল্যাব" },
  { id: "গ", depertment: "সায়েন্স ল্যাব" },
  { id: "৪", depertment: "জব প্লেসমেন্ট সেল" },
  { id: ".", depertment: "" },
  { id: "৬", depertment: "একাডেমিক" },
  { id: "৭", depertment: "জেনারেল" },
  { id: "৮", depertment: "হিসাব" },
  { id: "৯", depertment: "গ্রন্থাগার" },
  { id: "১০", depertment: "ও,সি নিরাপত্তা/কেয়ার টেকার" },
  { id: "১১", depertment: "জেনারেল স্টোর" },
];
